
version = "3.8.3"
runner.dialect = scala3

# Enforce a specific maximum width for code lines
maxColumn = 120

# Alignment rules (like aligning assignments or arrow matches)
align.preset = some
#align.arrowEnumeratorGenerator true

# Code rewrite rules that remove boilerplate
rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortImports
]

# Indentation settings
continuationIndent.defnSite = 2
danglingParentheses.preset = true
spaces.inImportCurlyBraces = true
